### ISSUE TITLE
Ask questions about dataset

### ISSUE THREAD

**Issue by zyfzhoubaomi** [Archer-Tatsu/head-tracking#1]
After reading your article, I thank you very much for opening up your database. But I have the following questions：
1：You represent the viewport position in two columns in the database. However, each row of data is not aligned with the position in the video. Does each row of data represent the position of the viewport in each frame? 
2：Can you provide the weights of different regions in NCP-PSNR calculation of omnidirectional video at different resolutions? 
Thank you very much! Best wishes

**Comment by Archer-Tatsu** [comment]
Sorry for the late reply.
A1: The first row of viewing direction of each subject correspond to the first frame of the video, and the data is recorded in a fixed rate. You can obtain this rate via dividing the duration by the number of data. Hope this helps you.
A2: Of course. I'm working on make our code open source. The pre-calculated weight map will also be released. However, this may take several days. I'll inform you if it is ready.

**Comment by zyfzhoubaomi** [comment]
Thank you very much for your reply.
